deployment:
  myRegion:
    dev: eu-central-1
    test: eu-central-1
    prod: eu-west-1
  myProfile:
    dev: shop-reporter
    test: shop-reporter
    prod: shop-reporter
  myStage: ${opt:stage, self:provider.stage}