env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  semi: 0
  line-break-style: 0
  linebreak-style: 0
  no-use-before-define: 0
  import/prefer-default-export: 0
  comma-dangle: 0
  no-console: 0
  import/no-extraneous-dependencies: 0