@host = https://gn5o5h1kf8.execute-api.eu-central-1.amazonaws.com/dev

####
# getAll
GET {{ host }}/perfume


####
# create
POST {{ host }}/perfume
Content-Type: application/json

{
    "brand": "Hugo dsada",
    "model": "aaaa",
    "capacity": 50,
    "price": "100.99"
}

####
# getById
GET {{ host }}/perfume/bdb29453-c0db-42d5-a727-ed758ddfb262

####
# updatePerfume
PUT {{ host }}/perfume/bdb29453-c0db-42d5-a727-ed758ddfb262
Content-Type: application/json

{
    "brand": "zaktualizowany brand",
    "capacity": 99999
}

####
# removePerfume
DELETE {{ host }}/perfume/2e297fd6-fbf3-4826-bb88-139bf56f4dde